pull_request:
    - beefore:
        name: Prebuild checks
        subtasks:
            - eslint:
                name: JavaScript lint checks
                task: beefore
            - pycodestyle:
                name: Python lint checks
                task: beefore
    - smoke-test:
        task: batavia-py34
        name: Smoke build (Python 3.4)
        profile: hi-cpu
    - full-test:
        subtasks:
            - py3.5:
                name: Python 3.5 tests
                task: batavia-py35
            - py3.6:
                name: Python 3.6 tests
                task: batavia-py36
        profile: hi-cpu
push:
    - smoke-test:
        task: py34
        name: Smoke build (Python 3.4)
        profile: hi-cpu
